name: Escaneo con gitleaks

on:
  push:
    branches:
      - main

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - name: Ejecutar gitleaks
        run: gitleaks detect --source . --exit-code 1 || (echo "Se han detectado fugas" && exit 1)
